name: pytest

on:
  push:
    branches:
      - master  # Your branch name
    paths:
      - '**/*.py'  # Trigger only for changes in Python files
  pull_request:
    branches:
      - master  # Your branch name
    paths:
      - '**/*.py'  # Trigger only for changes in Python files

jobs:
  test-python-3-13:
    name: Test with Python 3.13
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # This checks out your code to the runner

    - name: Set up Python 3.13
      uses: actions/setup-python@v3  # Sets up the specified Python version
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-gh-action.txt  # Install dependencies

    - name: Run tests with pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest --cov=BharatFinTrack --cov-report=xml  # Run tests and generate coverage report in XML format

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # This secret token should be added in your repository settings

  test-python-3-12:
    name: Test with Python 3.12
    runs-on: ubuntu-latest
    needs: test-python-3-13  # Runs only after the Python 3.12 tests complete

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # This checks out your code to the runner

    - name: Set up Python 3.12
      uses: actions/setup-python@v3  # Sets up the specified Python version
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-gh-action.txt  # Install dependencies

    - name: Run tests with pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest --cov=BharatFinTrack --cov-report=xml  # Run tests and generate coverage report in XML format

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # This secret token should be added in your repository settings

  test-python-3-11:
    name: Test with Python 3.11
    runs-on: ubuntu-latest
    needs: test-python-3-12  # Runs only after the Python 3.11 tests complete

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # This checks out your code to the runner

    - name: Set up Python 3.11
      uses: actions/setup-python@v3  # Sets up the specified Python version
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-gh-action.txt  # Install dependencies

    - name: Run tests with pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest --cov=BharatFinTrack --cov-report=xml  # Run tests and generate coverage report in XML format

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # This secret token should be added in your repository settings

  test-python-3-10:
    name: Test with Python 3.10
    runs-on: ubuntu-latest
    needs: test-python-3-11  # Runs only after the Python 3.11 tests complete

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # This checks out your code to the runner

    - name: Set up Python 3.10
      uses: actions/setup-python@v3  # Sets up the specified Python version
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-gh-action.txt  # Install dependencies

    - name: Run tests with pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest --cov=BharatFinTrack --cov-report=xml  # Run tests and generate coverage report in XML format

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # This secret token should be added in your repository settings